### ISSUE TITLE
Repository pattern (?)

### ISSUE THREAD

**Issue by alfonsovgs** [meysamhadeli/ecommerce-monolith#1]
First of all, thansk for sharing your work! 👌

I'm curious about the choice of using `ECommerceDbContext` instead of Repository pattern. Could you please elaborate on the reasons behind this decision?

**Comment by meysamhadeli** [comment]
> First of all, thansk for sharing your work! 👌
> 
> I'm curious about the choice of using `ECommerceDbContext` instead of Repository pattern. Could you please elaborate on the reasons behind this decision?

You're welcome, I hope this project was helpful for you :)
I am not fan of **repository pattern**, Because this pattern mostly use when we want:
1- **Change our database level** (we don't need it, because in vertical since architecture we can change our database level base on our slice, It is also rare that we want to change the database in the future!, so I prefer don't use repository pattern).
2- **Testing** (we can handle it with in memory database for test without having repository pattern).

Also, everyone may have our opinion and maybe someone like to use it with all of this reason (but I am not! :) )
This is a good resource about repository pattern that I follow that:
[Have you replaced your DB because of the Repository Pattern?](https://www.youtube.com/watch?v=EwKhyp2kHME)
